
import javax.swing.JRadioButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * action.java
 *
 * Created on 09-Jul-2011, 19:58:58
 */

/**
 *
 * @author Nafees Yousuf
 */
public class action extends javax.swing.JFrame {


    /** Creates new form action */
    public action(
            ) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        btnOk = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        r6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 24));
        jLabel1.setText("Welcome Admin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 156, 29);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        r2.setText("Search");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2);
        r2.setBounds(40, 100, 100, 27);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        r1.setText("Return Books");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(40, 120, 105, 27);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        r3.setText("Manage Categries");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3);
        r3.setBounds(40, 140, 127, 27);

        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        r4.setText("Add/Remove Books");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        getContentPane().add(r4);
        r4.setBounds(40, 160, 137, 27);

        buttonGroup1.add(r5);
        r5.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        r5.setText("Change Password");
        getContentPane().add(r5);
        r5.setBounds(40, 180, 125, 27);

        btnOk.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(60, 240, 70, 27);

        btnCancle.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnCancle.setText("Cancle");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancle);
        btnCancle.setBounds(140, 240, 80, 27);

        btnExit.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(230, 240, 70, 27);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 320, 190);

        buttonGroup1.add(r6);
        r6.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        r6.setText("Issue Books");
        getContentPane().add(r6);
        r6.setBounds(40, 80, 100, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
     
}//GEN-LAST:event_r2ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_r4ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_btnCancleActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if(r2.isSelected())
        {
            search obj = new search();
            obj.setVisible(true);
        }
         if(r1.isSelected())
        {
            ReturnBooks obj = new ReturnBooks();
            obj.setVisible(true);
        }
         if(r3.isSelected())
        {
            AddCategry obj = new AddCategry();
            obj.setVisible(true);
        }
         if(r4.isSelected())
        {
            AddorRemove obj = new AddorRemove();
            obj.setVisible(true);
        }
         if(r5.isSelected())
        {
            ChangePass obj = new ChangePass();
            obj.setVisible(true);
        }
        if(r6.isSelected())
        {
            Issue obj = new Issue();
            obj.setVisible(true);
        }

}//GEN-LAST:event_btnOkActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new action().setVisible(true);
                action a = new action();
                a.setVisible(true);
                a.setSize(400, 320);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    // End of variables declaration//GEN-END:variables




}
