
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCategry.java
 *
 * Created on 11-Jul-2011, 02:20:54
 */

/**
 *
 * @author Nafees Yousuf
 */
public class AddCategry extends javax.swing.JFrame {

    /** Creates new form AddCategry */
    public AddCategry() {
        initComponents();
    }
     public Connection con() throws SQLException, ClassNotFoundException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url = "jdbc:odbc:sa1";
        return DriverManager.getConnection(url);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategrynam = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnAction = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtboknam = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel1.setText("Add New Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 150, 40);

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel2.setText("Category ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 70, 30);
        getContentPane().add(txtCategrynam);
        txtCategrynam.setBounds(120, 130, 160, 20);

        btnAdd.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(30, 170, 70, 27);

        btnAction.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnAction.setText("Action");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAction);
        btnAction.setBounds(120, 170, 70, 27);

        btnExit.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(200, 170, 70, 27);

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel3.setText("BookName");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 90, 20);
        getContentPane().add(txtboknam);
        txtboknam.setBounds(120, 100, 160, 20);
        getContentPane().add(txtISBN);
        txtISBN.setBounds(120, 70, 160, 20);

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("ISBN No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 70, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
         action obj = new action();
            obj.setVisible(true);
    }//GEN-LAST:event_btnActionActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            Connection conn = con();
            Statement s = (Statement) conn.createStatement();
            String query = "insert into Category values('"+txtCategrynam.getText()+"','"+txtboknam.getText()+"','"+txtISBN.getText()+"')";
      s.executeUpdate(query);
       JOptionPane.showMessageDialog(rootPane, "SUCCESSFULL");
        conn.close();
        }catch(ClassNotFoundException ex){JOptionPane.showInternalMessageDialog(txtCategrynam, ex+"2");}
    catch(SQLException ex)
{
    JOptionPane.showInternalMessageDialog(txtCategrynam, ex+"1");
}
    }//GEN-LAST:event_btnAddActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCategry a = new AddCategry();
                a.setVisible(true);
                a.setSize(400, 320);
//                new AddCategry().setVisible(true);
            }
        });
    }
    Connection cn=null;
    Statement s=null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCategrynam;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtboknam;
    // End of variables declaration//GEN-END:variables

}
