
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddorRemove.java
 *
 * Created on 11-Jul-2011, 02:26:15
 */

/**
 *
 * @author Nafees Yousuf
 */
public class AddorRemove extends javax.swing.JFrame {

    /** Creates new form AddorRemove */
    public AddorRemove() {
        initComponents();
    }
  public Connection con() throws SQLException, ClassNotFoundException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url = "jdbc:odbc:sa1";
        return DriverManager.getConnection(url);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBoktitle = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        lblAuthrNam = new javax.swing.JLabel();
        txtAuthrNam = new javax.swing.JTextField();
        lblCategry = new javax.swing.JLabel();
        lblQuntity = new javax.swing.JLabel();
        txtCategry = new javax.swing.JTextField();
        txtQuntity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        boktitl = new javax.swing.JLabel();
        lblCateg = new javax.swing.JLabel();
        lblAuthr = new javax.swing.JLabel();
        txtBooktitl = new javax.swing.JTextField();
        txtauthr = new javax.swing.JTextField();
        txtCateg = new javax.swing.JTextField();
        lblqntitybook = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtquntyBook = new javax.swing.JTextField();
        lblQnutityRemov = new javax.swing.JLabel();
        txtqntiyRemove = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRemovr = new javax.swing.JButton();
        btnClr = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Action = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel1.setText("Add And Remove Books");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 190, 23);

        lblBoktitle.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblBoktitle.setText("Book Title");
        getContentPane().add(lblBoktitle);
        lblBoktitle.setBounds(40, 70, 80, 20);

        txtBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookTitleActionPerformed(evt);
            }
        });
        getContentPane().add(txtBookTitle);
        txtBookTitle.setBounds(130, 70, 140, 20);

        lblAuthrNam.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblAuthrNam.setText("Author Name");
        getContentPane().add(lblAuthrNam);
        lblAuthrNam.setBounds(40, 100, 80, 20);
        getContentPane().add(txtAuthrNam);
        txtAuthrNam.setBounds(130, 100, 140, 20);

        lblCategry.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblCategry.setText("Category");
        getContentPane().add(lblCategry);
        lblCategry.setBounds(50, 130, 60, 20);

        lblQuntity.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblQuntity.setText("Quantity");
        getContentPane().add(lblQuntity);
        lblQuntity.setBounds(50, 160, 60, 20);
        getContentPane().add(txtCategry);
        txtCategry.setBounds(130, 130, 140, 20);
        getContentPane().add(txtQuntity);
        txtQuntity.setBounds(130, 160, 140, 20);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 320, 170);

        btnAdd.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(200, 200, 70, 27);

        boktitl.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        boktitl.setText("Book Title");
        getContentPane().add(boktitl);
        boktitl.setBounds(50, 270, 80, 18);

        lblCateg.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblCateg.setText("Category");
        getContentPane().add(lblCateg);
        lblCateg.setBounds(50, 330, 50, 20);

        lblAuthr.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblAuthr.setText("Author Name");
        getContentPane().add(lblAuthr);
        lblAuthr.setBounds(40, 300, 80, 18);
        getContentPane().add(txtBooktitl);
        txtBooktitl.setBounds(160, 270, 140, 20);
        getContentPane().add(txtauthr);
        txtauthr.setBounds(160, 300, 140, 20);
        getContentPane().add(txtCateg);
        txtCateg.setBounds(160, 330, 140, 20);

        lblqntitybook.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblqntitybook.setText("Quantity Available Of");
        getContentPane().add(lblqntitybook);
        lblqntitybook.setBounds(20, 360, 130, 20);

        jLabel7.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        jLabel7.setText("Book Selected");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 380, 90, 20);
        getContentPane().add(txtquntyBook);
        txtquntyBook.setBounds(160, 360, 140, 20);

        lblQnutityRemov.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblQnutityRemov.setText("Quantity To be Removed");
        getContentPane().add(lblQnutityRemov);
        lblQnutityRemov.setBounds(20, 400, 140, 18);
        getContentPane().add(txtqntiyRemove);
        txtqntiyRemove.setBounds(160, 400, 140, 20);

        jLabel9.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        jLabel9.setText("Of Book Selected");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 420, 110, 18);

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remove Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 220, 310, 230);

        btnRemovr.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnRemovr.setText("Remove");
        btnRemovr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovrActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemovr);
        btnRemovr.setBounds(150, 460, 80, 27);

        btnClr.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnClr.setText("Clear");
        btnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrActionPerformed(evt);
            }
        });
        getContentPane().add(btnClr);
        btnClr.setBounds(280, 200, 70, 27);

        jButton2.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        jButton2.setText("Clear");
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 460, 70, 27);

        Action.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        Action.setText("Action");
        getContentPane().add(Action);
        Action.setBounds(60, 460, 80, 27);

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("ISBN No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 40, 70, 18);
        getContentPane().add(txtISBN);
        txtISBN.setBounds(130, 40, 140, 20);

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("ISBN No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 250, 80, 18);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 240, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = con();
            Statement s = (Statement) conn.createStatement();
            String query = "insert into AddRemoveBooks values('"+txtBookTitle.getText()+"', '"+txtAuthrNam.getText()+"','"+txtCategry.getText()+"',"+txtQuntity.getText()+")";
        s.executeUpdate(query);
         JOptionPane.showMessageDialog(rootPane, "SUCCESSFULL");
        conn.close();
        }catch(ClassNotFoundException ex){JOptionPane.showInternalMessageDialog(txtBookTitle, ex+"2");}
    catch(SQLException ex)
{
    JOptionPane.showInternalMessageDialog(txtBookTitle, ex+"1");
}

}//GEN-LAST:event_btnAddActionPerformed

    private void btnRemovrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovrActionPerformed
           try{
            Connection conn = con();
            Statement s = (Statement) conn.createStatement();
            String query = "Delete from AddRemoveBooks where BookTitle='"+txtBooktitl.getText()+"'";
        s.executeUpdate(query);
         JOptionPane.showMessageDialog(rootPane, "SUCCESSFULL");
        conn.close();
        }catch(ClassNotFoundException ex){JOptionPane.showInternalMessageDialog(txtBookTitle, ex+"2");}
    catch(SQLException ex)
{
    JOptionPane.showInternalMessageDialog(txtBookTitle, ex+"1");
}
    }//GEN-LAST:event_btnRemovrActionPerformed

    private void btnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrActionPerformed
      txtBookTitle.setText("");
      txtAuthrNam.setText("");
      txtCategry.setText("");
      txtQuntity.setText("");
}//GEN-LAST:event_btnClrActionPerformed

    private void txtBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookTitleActionPerformed
  
    }//GEN-LAST:event_txtBookTitleActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddorRemove().setVisible(true);
            }
        });
    }
Connection cn=null;
    Statement s=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action;
    private javax.swing.JLabel boktitl;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClr;
    private javax.swing.JButton btnRemovr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAuthr;
    private javax.swing.JLabel lblAuthrNam;
    private javax.swing.JLabel lblBoktitle;
    private javax.swing.JLabel lblCateg;
    private javax.swing.JLabel lblCategry;
    private javax.swing.JLabel lblQnutityRemov;
    private javax.swing.JLabel lblQuntity;
    private javax.swing.JLabel lblqntitybook;
    private javax.swing.JTextField txtAuthrNam;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtBooktitl;
    private javax.swing.JTextField txtCateg;
    private javax.swing.JTextField txtCategry;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtQuntity;
    private javax.swing.JTextField txtauthr;
    private javax.swing.JTextField txtqntiyRemove;
    private javax.swing.JTextField txtquntyBook;
    // End of variables declaration//GEN-END:variables

}
