
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChangePass.java
 *
 * Created on 11-Jul-2011, 03:38:31
 */

/**
 *
 * @author Nafees Yousuf
 */
public class ChangePass extends javax.swing.JFrame {

    /** Creates new form ChangePass */
    public ChangePass() {
        initComponents();
        try{
            Connection cn=con();
            ps=cn.prepareStatement("select  * from Register");
           rs=ps.executeQuery(); 
           rs.next();
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }catch(ClassNotFoundException ex){
             JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
   public Connection con() throws SQLException, ClassNotFoundException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url = "jdbc:odbc:sa1";
        return DriverManager.getConnection(url);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOldPas = new javax.swing.JLabel();
        lblNewPas = new javax.swing.JLabel();
        lblCnfrmPas = new javax.swing.JLabel();
        txtNewPas = new javax.swing.JPasswordField();
        txtCnfrmPas = new javax.swing.JPasswordField();
        btnSav = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtOldPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtusrname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel1.setText("Change Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 150, 30);

        lblOldPas.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblOldPas.setText("Old Password");
        getContentPane().add(lblOldPas);
        lblOldPas.setBounds(60, 70, 90, 20);

        lblNewPas.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblNewPas.setText("New Password");
        getContentPane().add(lblNewPas);
        lblNewPas.setBounds(60, 100, 90, 20);

        lblCnfrmPas.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblCnfrmPas.setText("Confirm New Password");
        getContentPane().add(lblCnfrmPas);
        lblCnfrmPas.setBounds(30, 130, 140, 20);
        getContentPane().add(txtNewPas);
        txtNewPas.setBounds(180, 100, 130, 20);

        txtCnfrmPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnfrmPasActionPerformed(evt);
            }
        });
        getContentPane().add(txtCnfrmPas);
        txtCnfrmPas.setBounds(180, 130, 130, 20);

        btnSav.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnSav.setText("Save");
        btnSav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavActionPerformed(evt);
            }
        });
        getContentPane().add(btnSav);
        btnSav.setBounds(60, 170, 80, 30);

        btnCancle.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnCancle.setText("Cancle");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancle);
        btnCancle.setBounds(240, 170, 80, 30);

        btnClear.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(150, 170, 80, 30);
        getContentPane().add(txtOldPass);
        txtOldPass.setBounds(180, 70, 130, 20);

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 40, 70, 18);
        getContentPane().add(txtusrname);
        txtusrname.setBounds(180, 40, 130, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_btnCancleActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtusrname.setText("");
        txtOldPass.setText("");
        txtNewPas.setText("");
        txtCnfrmPas.setText("");
}//GEN-LAST:event_btnClearActionPerformed

    private void btnSavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavActionPerformed

        if(txtNewPas.getText().equals(txtCnfrmPas.getText())){
        try{
            Connection conn = con();
            Statement s = conn.createStatement();
            String query = "UPDATE  Register SET  UserName ='"+txtusrname.getText()+"',pass='"+txtNewPas.getText()+", ConfirmPass ='"+txtCnfrmPas.getText()+"'";
            JOptionPane.showMessageDialog(rootPane, "SUCCESSFULL");
        s.executeUpdate(query);
        conn.close();
        }catch(ClassNotFoundException ex){JOptionPane.showMessageDialog(txtOldPass, ex+"2");}
    catch(SQLException ex)
{
    JOptionPane.showMessageDialog(txtOldPass, ex+"1");
}
        }else {
            JOptionPane.showMessageDialog(rootPane,"plz re enter pass");
        }
//        } catch (SQLException ex) {
//          JOptionPane.showMessageDialog(rootPane, ex.getMessage());
//        }

    }//GEN-LAST:event_btnSavActionPerformed

    private void txtCnfrmPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnfrmPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnfrmPasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               ChangePass a = new ChangePass();
                a.setVisible(true);
                a.setSize(400, 320);
//                new ChangePass().setVisible(true);
            }
        });
    }




    Connection cn=null;
    Statement s=null;
    PreparedStatement ps=null;
    ResultSet rs=null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCnfrmPas;
    private javax.swing.JLabel lblNewPas;
    private javax.swing.JLabel lblOldPas;
    private javax.swing.JPasswordField txtCnfrmPas;
    private javax.swing.JPasswordField txtNewPas;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JTextField txtusrname;
    // End of variables declaration//GEN-END:variables

}
