
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Regster.java
 *
 * Created on 11-Jul-2011, 03:26:22
 */

/**
 *
 * @author Nafees Yousuf
 */
public class Regster extends javax.swing.JFrame {

    /** Creates new form Regster */
    public Regster() {
        initComponents();
    }

    public Connection con() throws SQLException, ClassNotFoundException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url = "jdbc:odbc:sa1";
        return DriverManager.getConnection(url);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUsrNam = new javax.swing.JLabel();
        lblPas = new javax.swing.JLabel();
        lblCnfrmPas = new javax.swing.JLabel();
        txtUrName = new javax.swing.JTextField();
        txtPas = new javax.swing.JPasswordField();
        txtCnfrmPas = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 24));
        jLabel1.setText("Register User");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 150, 30);

        lblUsrNam.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblUsrNam.setText("UserName");
        getContentPane().add(lblUsrNam);
        lblUsrNam.setBounds(70, 50, 70, 18);

        lblPas.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblPas.setText("Password");
        getContentPane().add(lblPas);
        lblPas.setBounds(70, 80, 60, 18);

        lblCnfrmPas.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblCnfrmPas.setText("Confirm Password");
        getContentPane().add(lblCnfrmPas);
        lblCnfrmPas.setBounds(40, 110, 104, 18);
        getContentPane().add(txtUrName);
        txtUrName.setBounds(150, 50, 160, 20);
        getContentPane().add(txtPas);
        txtPas.setBounds(150, 80, 160, 20);
        getContentPane().add(txtCnfrmPas);
        txtCnfrmPas.setBounds(150, 110, 160, 20);

        btnRegister.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(20, 170, 90, 30);

        btnClear.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(210, 170, 80, 30);

        btnExit.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(270, 210, 70, 27);

        btnLogin.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(120, 170, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
  txtUrName.setText("");
  txtPas.setText("");
  txtCnfrmPas.setText("");
        
}//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
         if(txtPas.getText().equals(txtCnfrmPas.getText())){
        try{
            Connection conn = con();
            Statement s = (Statement) conn.createStatement();
            String query = "insert into Register values('"+txtUrName.getText()+"', '"+txtPas.getPassword()+"', '"+txtCnfrmPas.getPassword()+"')";
      s.executeUpdate(query);
       JOptionPane.showMessageDialog(rootPane, "SUCCESSFULL");
        conn.close();
        }catch(ClassNotFoundException ex){JOptionPane.showInternalMessageDialog(txtUrName, ex+"2");}
    catch(SQLException ex)
{
    JOptionPane.showInternalMessageDialog(txtUrName, ex+"1");
}
        }else {
            JOptionPane.showMessageDialog(rootPane,"plz re enter pass");
        }
}//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        dispose();
        new logn().setVisible(true);
              logn a = new logn();
                a.setVisible(true);
                a.setSize(400, 320);

}//GEN-LAST:event_btnLoginActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Regster a = new Regster();
                a.setVisible(true);
                a.setSize(400, 320);
//                new Regster().setVisible(true);
            }
        });
    }
 Connection cn=null;
    Statement s=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCnfrmPas;
    private javax.swing.JLabel lblPas;
    private javax.swing.JLabel lblUsrNam;
    private javax.swing.JPasswordField txtCnfrmPas;
    private javax.swing.JPasswordField txtPas;
    private javax.swing.JTextField txtUrName;
    // End of variables declaration//GEN-END:variables

}
