
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReturnBooks.java
 *
 * Created on 11-Jul-2011, 01:53:11
 */

/**
 *
 * @author Nafees Yousuf
 */
public class ReturnBooks extends javax.swing.JFrame {

    /** Creates new form ReturnBooks */
    public ReturnBooks() {
        initComponents();
        
    }
    public Connection con() throws SQLException, ClassNotFoundException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url = "jdbc:odbc:sa1";
        return DriverManager.getConnection(url);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comBooknam = new javax.swing.JComboBox();
        txtCategory = new javax.swing.JTextField();
        btnRetrn = new javax.swing.JButton();
        btnAction = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblBokNam = new javax.swing.JLabel();
        lblCategry = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIssueDat = new javax.swing.JTextField();
        txtDueDat = new javax.swing.JTextField();
        txtRetrnDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel1.setText("Select Books To Be Retruned");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 230, 30);

        comBooknam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "abc" }));
        comBooknam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBooknamActionPerformed(evt);
            }
        });
        getContentPane().add(comBooknam);
        comBooknam.setBounds(120, 70, 210, 20);
        getContentPane().add(txtCategory);
        txtCategory.setBounds(120, 100, 180, 20);

        btnRetrn.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnRetrn.setText("Return");
        btnRetrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrnActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetrn);
        btnRetrn.setBounds(50, 250, 71, 30);

        btnAction.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnAction.setText("Action");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAction);
        btnAction.setBounds(140, 250, 70, 30);

        btnExit.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(240, 250, 80, 30);

        lblBokNam.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblBokNam.setText("Book Name");
        getContentPane().add(lblBokNam);
        lblBokNam.setBounds(40, 70, 70, 18);

        lblCategry.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblCategry.setText("Category");
        getContentPane().add(lblCategry);
        lblCategry.setBounds(50, 100, 60, 18);

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        jLabel2.setText("IssueDate");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 130, 70, 18);

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        jLabel3.setText("DueDate");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 60, 20);

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        jLabel4.setText("ReturnBook");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 80, 20);
        getContentPane().add(txtIssueDat);
        txtIssueDat.setBounds(130, 130, 140, 20);
        getContentPane().add(txtDueDat);
        txtDueDat.setBounds(130, 160, 140, 20);
        getContentPane().add(txtRetrnDate);
        txtRetrnDate.setBounds(130, 190, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comBooknamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBooknamActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comBooknamActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
            action obj = new action();
            obj.setVisible(true);
    }//GEN-LAST:event_btnActionActionPerformed

    private void btnRetrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrnActionPerformed
          try{
            Connection conn = con();
            Statement s = (Statement) conn.createStatement();
            String query = "Delete from Issue where (BookName='"+comBooknam+"')";
        s.executeUpdate(query);
         JOptionPane.showMessageDialog(rootPane, "SUCCESSFULL");
        conn.close();
        }catch(ClassNotFoundException ex){JOptionPane.showInternalMessageDialog(comBooknam, ex+"2");}
    catch(SQLException ex)
{
    JOptionPane.showInternalMessageDialog(comBooknam, ex+"1");
}
    }//GEN-LAST:event_btnRetrnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReturnBooks a = new ReturnBooks();
                a.setVisible(true);
                a.setSize(400, 320);
//                new ReturnBooks().setVisible(true);
            }
        });
    }
   Connection cn=null;
    Statement s=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRetrn;
    private javax.swing.JComboBox comBooknam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBokNam;
    private javax.swing.JLabel lblCategry;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDueDat;
    private javax.swing.JTextField txtIssueDat;
    private javax.swing.JTextField txtRetrnDate;
    // End of variables declaration//GEN-END:variables

}
