

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * search.java
 *
 * Created on 10-Jul-2011, 15:24:25
 */

/**
 *
 * @author Nafees Yousuf
 */
public class search extends javax.swing.JFrame {

    /** Creates new form search */
    public search() {
        initComponents();
    }
    public Connection con() throws SQLException, ClassNotFoundException
    {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        String url = "jdbc:odbc:naf";
        return DriverManager.getConnection(url);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblBookNam = new javax.swing.JLabel();
        txtlBooknam = new javax.swing.JTextField();
        lblCategry = new javax.swing.JLabel();
        txtCategy = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAction = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel1.setText("Note: If multiple selection criteria are entered result ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 390, 20);

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 18));
        jLabel2.setText("displayed will beb retrive using and confidition");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 350, 20);

        lblCategory.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Criteria-Enter Atleaset One Criteria "));
        getContentPane().add(lblCategory);
        lblCategory.setBounds(60, 130, 280, 140);

        lblBookNam.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblBookNam.setText("Book Name");
        getContentPane().add(lblBookNam);
        lblBookNam.setBounds(90, 180, 70, 20);
        getContentPane().add(txtlBooknam);
        txtlBooknam.setBounds(170, 180, 130, 20);

        lblCategry.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        lblCategry.setText("Category");
        getContentPane().add(lblCategry);
        lblCategry.setBounds(100, 210, 60, 20);
        getContentPane().add(txtCategy);
        txtCategy.setBounds(170, 210, 130, 20);

        btnSearch.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(60, 300, 73, 30);

        btnAction.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnAction.setText("Action");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAction);
        btnAction.setBounds(150, 300, 80, 30);

        btnExit.setFont(new java.awt.Font("Script MT Bold", 0, 14));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(240, 300, 80, 30);

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 0, 24));
        jLabel3.setText("Search Books");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 0, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_btnExitActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed

            action obj = new action();
            obj.setVisible(true);

}//GEN-LAST:event_btnActionActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
          try{
            Connection conn = con();
            Statement s = (Statement) conn.createStatement();
            String query = "select     BookName='"+txtlBooknam.getText()+"',Category= '"+txtCategy.getText()+"'  from  Search";
      s.executeUpdate(query);
       JOptionPane.showMessageDialog(rootPane, "SUCCESSFULL");
        conn.close();
        }catch(ClassNotFoundException ex){JOptionPane.showInternalMessageDialog(txtlBooknam, ex+"2");}
    catch(SQLException ex)
{
    JOptionPane.showInternalMessageDialog(txtlBooknam, ex+"1");
}
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                search a = new search();
                a.setVisible(true);
                a.setSize(400, 430);
//                new search().setVisible(true);
            }
        });
    }
 Connection cn=null;
    Statement s=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBookNam;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategry;
    private javax.swing.JTextField txtCategy;
    private javax.swing.JTextField txtlBooknam;
    // End of variables declaration//GEN-END:variables

}
